name: Lint Code Base

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Lint C++ Files
        run: |
          find . -type f \( -name '*.cpp' -o -name '*.h' \) | while read file; do
            echo "Linting $file"
            # Optionally check for tabs. Remove this block if tabs are allowed.
            if grep -P "\t" "$file"; then
              echo "Warning: Tabs found in $file. Consider replacing with spaces for consistency."
              exit 1
            fi
            
            # Check if file ends with a newline
            if [ "$(tail -c1 "$file" | wc -l)" -eq "0" ]; then
              echo "Warning: $file does not end with a newline. It's recommended to add one."
              exit 1
            fi
          done